### ISSUE TITLE
Disable / remove snapping

### ISSUE THREAD

**Issue by pmamat** [guidobouman/jquery-panelsnap#101]
Hello everybody,

First of all: thank you for this great plugin!

In my current usecase I would like to disable the snapping mechanism for small displays, because there is too much content to fit on a panel. Is there a way to disable the snapping -- a method to be called on resize / if the viewport size is too small? (and vice versa to re-enable the snapping?)

Thanks for your help!
Regards,
 Philipp

**Comment by guidobouman** [comment]
`$('.container').panelSnap('disable');`

and

`$('.container').panelSnap('enable');`
