### ISSUE TITLE
How can i move to top slide

### ISSUE THREAD

**Issue by harmandeep-singh** [guidobouman/jquery-panelsnap#102]
Hi,
Thanks for this great plugin, i am trying to use it but not figure out the way scroll  back top position(first slide) by my footer   ##link,
for example in my layout i already bind menu with plugin i want a back to top button on my footer section. is their any method for this ?
Thank you.

**Comment by guidobouman** [comment]
See: https://github.com/guidobouman/jquery-panelsnap#activating-panels-manually
