### ISSUE TITLE
can't get panels to snap

### ISSUE THREAD

**Issue by srikat** [guidobouman/jquery-panelsnap#103]
I am trying to get panelSnap working here: http://panelsnap.wpdemo.space/

I am loading jquery.panelSnap.js followed by initialising it in the footer on `.site-inner > div`.

When I scroll down or up, it doesn't snap like in the script demo.

Any ideas? Thanks in advance.

**Comment by guidobouman** [comment]
Your `.site-inner` is not the scrolling element, so panelSnap can't snap on that.
