### ISSUE TITLE
directionThreshold not working when using offset.

### ISSUE THREAD

**Issue by davroe** [guidobouman/jquery-panelsnap#106]
If using a offset, the value for directionThreshold is compared wrong.
You have to scroll at least (offset+directionThreshold) to snap.
Maybe relation with #78 as scrollStop funtion is called twice...

**Comment by guidobouman** [comment]
Ouch, we're only snapping when there's at least 2 panels in view... Won't fix for now.

**Comment by yoan1005** [comment]
Hi,
Same bug, have you fix it ??

**Comment by guidobouman** [comment]
For v1.0 the offset option is disappearing, this can be accounted for in CSS for now. Let me know if you have a scenario that still requires the offset option within the plugin.
