### ISSUE TITLE
Can't get panelsnap to work

### ISSUE THREAD

**Issue by plastik1man** [guidobouman/jquery-panelsnap#108]
I'm trying to get panelsnap to work but without luck. I created a codepen where I used some HTML i found here. I added the jquery.panelsnap.js into the JS code window.

http://codepen.io/anon/pen/VjONYP

What am I doing wrong?

**Comment by guidobouman** [comment]
You dan't have any panels, and you're trying to invoke panelSnap on a non-existing element.
