### ISSUE TITLE
Does not work with a non-body container.

### ISSUE THREAD

**Issue by mokargas** [guidobouman/jquery-panelsnap#11]
On Chrome 30, Windows 8.1. Haven't tested on any other browsers

Example: http://www.svelteteam.com/static/tyrecycle/panel-test.html

Removing the "base_layout" div and setting the container to body however will work. 

Example: http://www.svelteteam.com/static/tyrecycle/panel-test-2.html

Is there something I'm missing?

**Comment by alex-wane** [comment]
not works with custom html
http://jsfiddle.net/4ptcpvh4/1/embedded/result/

**Comment by guidobouman** [comment]
@alex-wane 
1. You should create a new issue, not reply on an old one.
2. You're calling panelSnap on your wrapper. But your wrapper is not a scrolling div. Call panelSnap on your body or make sure your wrapper is a scrolling element.

**Comment by alex-wane** [comment]
1. I did not want to create a similar theme
2. Thank you for your reply
3. In any case, the plugin will not work if we have a section wrapped in the HTML structure.
$('body').panelSnap(); - does not work.

**Comment by guidobouman** [comment]
Sorry, the numbers probably made me sound annoyed, that was not my intention.

Check out the demo's. It works over there.

If you have elements in between your panels & your scrolling element you should disable the strict selector option.

```$('body').panelSnap({
  strictContainerSelection: false
});```

**Comment by alex-wane** [comment]
Thank you for your reply and help. I apologize for my inattention =(
