### ISSUE TITLE
Page not being scrolled in Chrome 61

### ISSUE THREAD

**Issue by matmannion** [guidobouman/jquery-panelsnap#113]
Chrome 61 [finally makes scrolling spec-compliant](https://bugs.chromium.org/p/chromium/issues/detail?id=157855) which means that [142b816762eeb72fc72083c0da5812d72897ddcf](https://github.com/guidobouman/jquery-panelsnap/commit/142b816762eeb72fc72083c0da5812d72897ddcf) probably needs to be reverted, and we can probably use `document.scrollingElement` as a preference to `document.documentElement`.

panelSnap is broken in Chrome 61 at the moment due to this.

**Comment by VipSaran** [comment]
👍
