### ISSUE TITLE
Demo page last panel won't get displayed on iPhone 5 portrait

### ISSUE THREAD

**Issue by cliffordp** [guidobouman/jquery-panelsnap#12]
Cool script, but the demo page's last panel just won't display. Instead, it snaps back to the 2nd-to-last panel.

**Comment by dmorrow** [comment]
This is still an issue in iOS9 Safari.  Are there any work arounds?

**Comment by guidobouman** [comment]
I just released v0.15.1 yesterday. The new snapping mechanic should fix this.
