### ISSUE TITLE
Prevent scrolling past section on fast scroll

### ISSUE THREAD

**Issue by athanasiosbabasidis** [guidobouman/jquery-panelsnap#147]
Is it possible to prevent a fast scroll from scrolling past a section?

**Comment by guidobouman** [comment]
It is, but this package does not work that way. It enhances native scroll, it does not replace the scroll behaviour.

Building this behaviour on your own is not too hard. You don't need this package for that. See https://css-tricks.com/simple-swipe-with-vanilla-javascript/ for a tutorial.

If you can not -, or do not want to build this, there are libraries like https://swipe.js.org/
