### ISSUE TITLE
PanelSnap does not support space between panels, snapping back.

### ISSUE THREAD

**Issue by najeeboffice** [guidobouman/jquery-panelsnap#152]
It is not working on this URL https://wqbb7aewk84xxnlc-26284064823.shopifypreview.com/

Latest Chrome, Firefox etc having same issue.

      jQuery(function () {
		var defaultOptions = {
		container: document.body,
		panelSelector: 'main > .shopify-section',
		directionThreshold: 0,
		delay: 0,
		duration: 300,
		easing: function(t) { return t },
		};

		new PanelSnap(defaultOptions);
      })

CSS:
body { min-height: 100vh; }
#PageContainer, #MainContent, .shopify-section.najeeb-img-picker {  min-height: 100vh; }

**Comment by guidobouman** [comment]
Got it fixed in the end? Your demo does not work anymore.

**Comment by najeeboffice** [comment]
> Got it fixed in the end? Demo does not work anymore.

lol no i just used another one. Scrollify !!!!

**Comment by guidobouman** [comment]
Hmkay. The plugin should work correctly. Check the demo's at https://panelsnap.com/
