### ISSUE TITLE
Use without npm in plain html/js/css project

### ISSUE THREAD

**Issue by aasutossh** [guidobouman/jquery-panelsnap#153]
downloading the panelsnap.js and sourcing it in html file throws error about not being able to find tweezer.js.

**Comment by guidobouman** [comment]
You're referring to the source code of the plugin. That's not meant to be consumed by applications directly.

Either do one of the following:
- Install from npm and consume the npm package **(RECOMMENDED)**
- Use the compiled version from the `docs` folder if you download the release from Github
- Check out the branch, run install & build steps to compile the plugin, and use the compiled plugin **(only for contributors)**
