### ISSUE TITLE
Snap To Next Element Immediately 

### ISSUE THREAD

**Issue by Dheirya** [guidobouman/jquery-panelsnap#154]
I'm not sure if anyone is still working on this repository, but...

I'm trying to make a tiktok-style website and I need the scroll to snap immediately; even before the user stops scrolling, because I want to make the scrolling feel "natural" and I want it to feel like scrolling on Tiktok.

**Edit:** I know this thread exists (https://github.com/guidobouman/panelsnap/issues/68), but it doesn't have a solution so I'm just gonna keep this up in case anyone notices.

**Comment by guidobouman** [comment]
Heya!

Author here.

For your case, the native scroll-snap CSS property might be a better solution:
https://codepen.io/ellie_html/pen/dyYjZyB

No JS library needed. 🎉

**Comment by Dheirya** [comment]
Thanks for the response! 

It's been a while since I created this issue, and I've moved on and actually don't need this feature anymore.

Thanks for the reply still, will definitely keep note of this!

**Comment by guidobouman** [comment]
Example:
https://codepen.io/ellie_html/pen/dyYjZyB
