### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'dataset')

### ISSUE THREAD

**Issue by jgax87** [guidobouman/jquery-panelsnap#172]
I am using the basic set up for panel snap and I get this error within my console

panelsnap.js?ver=6.2:8 Uncaught TypeError: Cannot read properties of null (reading 'dataset')
    at new t (panelsnap.js?ver=6.2:8:5655)
    at HTMLDocument.<anonymous> ((index):200:28)

the line it is referencing to is this
this.options.container.dataset.panelsnapId)

**Comment by guidobouman** [comment]
It seems like `container` can not be found. Did you properly configure it in your `config` object? Or alternatively, did you make sure the container element from the demos is present in your html?
