### ISSUE TITLE
Add an offset option

### ISSUE THREAD

**Issue by commonpike** [guidobouman/jquery-panelsnap#33]
Thanks for a great plugin.

I just hacked in an offset option so that element dont snap to the screen top (or container top), but on a specified offset below it. in my case there was a css fixed element hanging on the top of the page and i wanted content to snap unto that.

**Comment by dpaquette** [comment]
:+1:  This features is needed for my usage as well.

**Comment by guidobouman** [comment]
I'm closing this one as #71 is going to fix this.
