### ISSUE TITLE
scrollStop doesn't fire when scrolling in nested element before scrollStop has fired.

### ISSUE THREAD

**Issue by guidobouman** [guidobouman/jquery-panelsnap#62]
Can be fixed by properly isolating scrollstart/scrollstop instances.

**Comment by mrksmts** [comment]
Guess this also explains why panelsnap stays so persistent in going to a specific panel while I scroll towards a different panel.

**Comment by guidobouman** [comment]
Well, it shouldn't. You should only have issues with it not snapping anywhere when scrolling in a nested element.

**Comment by mrksmts** [comment]
Then the issue I described might be another one, but might relate to the nested element.

While panelsnap is animating to a specific panel and you scroll in the opposite direction (while it is animating) it stays persistent in going to the previous location, till you scroll past the panel that it is trying to animate to.

**Comment by guidobouman** [comment]
Can you open a new issue with a testcase I can look at, and in which browsers this happens?

**Comment by Unit60** [comment]
Not sure if this is the right place and I am only an enthusiast, but might it be an idea to detect the initial scroll direction and then force that direction (to the next anchor) rather than a rule of proximity and attraction... that may solve the issue of mrksmts's 'persistance' problem and also perhaps the section hight's wouldn't have to be fixed at 100% in order for a more diverse and better user experience?!

**Comment by guidobouman** [comment]
You should open another issue for this, as it's unrelated to the issue mentioned as the title of this thread.

Also, his persistence problem has been fixed already as can be seen in the issue he opened.

The way the current system works is that it's detecting an amount of slack around the panel edges, after that it snaps the first panel based on intention / direction, if you scroll more than one panel at once, it rounds to the nearest panel. That's because the plugin fires after the current scroll has come to a standstill. If you end up at two panels and a little bit, it should not skip that panel that almost fully in screen. It doesn't make sense. What you're suggesting is where this plugin came from initially.

**Comment by Unit60** [comment]
I was unaware of that, i am a gitub novice, but really appreciate that you answered :)

**Comment by guidobouman** [comment]
I mean, back in the early days this plugin used to work like that. Later on, I replaced that behaviour in favor of the current one. I'm not going to change this back. =]

You're welcome to fork this plugin and change it to the way you like.

**Comment by guidobouman** [comment]
@Unit60 The plugin is changing behaviour in favor of predictability. Check out the latest build to test this new behaviour: It's always snapping in the direction the user was scrolling.

**Comment by guidobouman** [comment]
Fixed in 21bcbe9842a4d8f3ea0620c03dfd2f928814b2d9, this will land with the v1.0 release.
