### ISSUE TITLE
Add horizontal snapping functionality

### ISSUE THREAD

**Issue by guidobouman** [guidobouman/jquery-panelsnap#7]
Horizontal snapping functionality is currently not present. Can this be added without increasing the plugin footprint unreasonably? 

Opinions on wether or not you think this is crucial please.

**Comment by UAMike** [comment]
+1

**Comment by 1GR3** [comment]
+1

**Comment by JWestarp** [comment]
+1 :+1:

**Comment by andri** [comment]
+1 :)

**Comment by Rockster160** [comment]
+1

**Comment by jromme** [comment]
@JWestarp @Gaffen @gerwitz 
The guys with the deadlines: What did you do to fix it? Or did you go for some other design?

**Comment by JWestarp** [comment]
I choosed an other design (horizontal) because it's better for usablity.

**Comment by andri** [comment]
@jromme, I used a custom solution in my case, this is based on something I found somewhere, can't remember where. Works pretty well for me.

```javascript
function snap() {
	var elementWidth = 200;
	var scrollPos = $(".container").scrollLeft();
	var newPos = Math.round(scrollPos / elementWidth) * elementWidth;
	$(".container").stop().animate({scrollLeft: newPos}, 400);
	$(".container").stop().animate({scrollLeft: newPos}, 400);
}
```

**Comment by Rockster160** [comment]
I also wrote a solution myself. It's not perfect by any means, and I made it pretty specific to my case (the type of horizontal snap I'm using isn't commonly used).

**Comment by guidobouman** [comment]
Good news for the people that are still interested in horizontal snapping. I'm on a 6 week release cycle now, to improve the quality of this plugin. 

V0.15.0 is due the 5th of Juli, it'll contain snapping for flexible size panels.
V1.0 is due the 16th of August, it'll have horizontal snapping!

**Comment by jromme** [comment]
@guidobouman: That would be a great addition to a already great plugin. Thank you!

**Comment by gerwitz** [comment]
Nice!

Are you looking at "fall forward" to CSS snappoints? I was just about to modify my homegrown carousel for them, but remain eager to throw away my invented wheel.

(It's too soon, yes, but it won't be long: http://caniuse.com/#feat=css-snappoints )

**Comment by guidobouman** [comment]
Oh snap! (pun intended...) Thanks for reminding me about that.

Can you open up a new issue @gerwitz? I'll put it on the roadmap. I'd love my plugin to become useless. Back when I saw it, I'd swear it was in not a single browser. Lets see if we can get a working version soon!

**Comment by bomalley** [comment]
Checking in for progress on this feature.  Any news on V0.15 or V1.0?

Really in need of a horizontal snapping solution.  Thanks for this great plugin!

**Comment by Gaffen** [comment]
Probably a bit late, but for my deadline I believe I ended up using [jquery.snapscroll](https://github.com/wtm/jquery.snapscroll), with a little bit of hacking re. scroll orientation

**Comment by leeprobert** [comment]
Are you ready with v1.0. Need the horizontal snapping!

:-)

**Comment by ScottBeeson** [comment]
+1 for horizontal functionality.
