### ISSUE TITLE
Implementation Problems

### ISSUE THREAD

**Issue by b12n** [guidobouman/jquery-panelsnap#72]
Hey Guido, 

Thanks a lot for writing and maintaining panelsnap. I'd like to use it, but am having some issues integrating it into my rails project. Chiefly, I'm confused with the script tags, and where these should go. 

Thanks in advance. 

Best, 
Brendan

**Comment by b12n** [comment]
The <script> calls, that is

**Comment by guidobouman** [comment]
You should probably include this like any other script. If you already have jQuery in your project, include the plugin after jQuery.

Some people put `script` tags in the `head` section of their website, other put it at the bottom of the `body`. Although in the documentation I use the first option for simplicity, for speed optimisations I advice the latter.

**Comment by b12n** [comment]
Fantastic, thank you for the help.
