### ISSUE TITLE
Panelsnap stays persistent in animation direction

### ISSUE THREAD

**Issue by mrksmts** [guidobouman/jquery-panelsnap#73]
I've setup an example for this issue:
http://jsfiddle.net/bw2edtb6/1/

Steps to reproduce:
- Scroll down enough for panelsnap to start animating to the next panel
- Before it finishes animating
- Scroll back up around 100px or so
- Stop scrolling
- Panelsnap will still continue to scroll for the next panel instead of the previous

Tested on Retina MacBook Pro, OSX 10.10, Chrome 39.0 and Safari 8.0

**Comment by guidobouman** [comment]
The actual error: `ScrollOffset is not updated when snapping is interrupted.`

Good find. I'll fix this today. I have the solution. Just need to commit it, and update in the demo.

**Comment by mrksmts** [comment]
That's great, might have found another issue, but haven't been able to reproduce that. 
Will let you know when I figure that out.

**Comment by guidobouman** [comment]
Fixed in #74
