### ISSUE TITLE
Delay before scroll

### ISSUE THREAD

**Issue by olach** [guidobouman/jquery-panelsnap#75]
This is a feature request that would be nice. What I would like to see is a possibility to have a small delay before the plugin starts scrolling and snaps the panel in place. This way, the automatic scrolling would be less disruptive to the user.

This webpage has the functionality I'm describing. Scroll the page, wait like 2 seconds, and then watch the page scroll in place.
http://risenchurch.com/

**Comment by guidobouman** [comment]
Thanks for your suggestion, I'll implement this sometime soon. Probably somewhere in the coming days.

**Comment by AllanD** [comment]
I would like this feature too.  Has it been implimented?

**Comment by guidobouman** [comment]
Fixed in #76
