### ISSUE TITLE
snapToPanel gets called too many times

### ISSUE THREAD

**Issue by jmouka** [guidobouman/jquery-panelsnap#78]
The first time it's called is from the user's scrollStop event, but then it gets called again from the snapping scrollStop event. That is, when it finishes snapping, it triggers animate's "complete" callback, sets the isSnapping to false, and the dom triggers scrollStop again. One way to fix this is to delay setting isSnapping=false, e.g. in the animate "complete" callback:

setTimeout(function() {
     self.isSnapping = false;
}, 100);

**Comment by guidobouman** [comment]
Delaying this a bit as it's not crucial to the functionality, and fixing it involves more than delaying the snapping release.

**Comment by guidobouman** [comment]
Fixed with b3e8678304e20084bf9dcb8786742b0b521a7a38
