### ISSUE TITLE
Scrolling to next section from a fixed button

### ISSUE THREAD

**Issue by RussellJonesPersonal** [guidobouman/jquery-panelsnap#79]
Hi

I love panelsnap!  Apologies if this has been asked/resolved, but I haven't been able to find it. And apologies if I'm posting this in the wrong place - also new to Github!

I have a design which requires a fixed toolbar, containing a "down" button. I'd like this button to scroll down to the next section onClick - a link performing the equivalent of "keydown". I can't do this targeting named sections, because the button remains fixed, so need it to scroll to "next".

I'm not a hardcore coder, and this level of Jquery is beyond me. Any help would be very welcome!

**Comment by guidobouman** [comment]
Actually, it's quite easy. The (undocumented) panelSnap API allows for the following commands:

`$('.container').panelSnap('snapTo', 'next');` & `$('.container').panelSnap('snapTo', 'prev');`

This allows you to cycle through panels with the use of buttons.
