### ISSUE TITLE
snap not working in 50vh

### ISSUE THREAD

**Issue by cristofersousa** [guidobouman/jquery-panelsnap#81]
Sections that should not own 100% of the time, and if setted 50% it crashes.
Sections que não devem possuir 100% de altura, e se for setado com 50% ele trava.

 http://jsfiddle.net/korzzus/uspzc5qy/11/

**Comment by guidobouman** [comment]
Right now the plugin is designed to work with full screen panels. I'm implementing a different snapping algorithm which might fix snapping to panels of different sizes as well.

**Comment by kcroakeJRD** [comment]
Did you ever figure out that algorithm? or know of an alternative solution? 

Thanks love the plugin!
