### ISSUE TITLE
Snapping doesn't stop and runs to the end of the page

### ISSUE THREAD

**Issue by T27M** [guidobouman/jquery-panelsnap#85]
I'm having an issue where the snap doesn't stop and will continue right to the bottom of the webpage. I built my site using this template http://startbootstrap.com/template-overviews/scrolling-nav/

It seems to work ok when viewing the site in full size, but on re-sizing the snap fails and does what I have described above.

**Comment by guidobouman** [comment]
Do you have a live demo? This is not a lot of info to go by.

**Comment by T27M** [comment]
Sorry for the delay and lack of information I was in a rush when I posted the issue. This site is a WIP. Once you get below about 400px width, it behaves as I described above.

http://crimsonnight.com/kamigami/kami-bootstrap/
