### ISSUE TITLE
Is not loading element inside body

### ISSUE THREAD

**Issue by albertogil** [guidobouman/jquery-panelsnap#87]
Hi,

I added the plugin to [my site](http://nuevo.eventoscarlosgil.com/) with a container of fixed height and overflow scroll; and binding it with `$('.homeSlider').panelSnap({ strictContainerSelection: false });`

I am missing something to make it work?

Thanks,

Alberto

**Comment by guidobouman** [comment]
Well, if you read the documentation, your selection is not set up properly. This should fix your implementation:

```
$('.homeSlider').panelSnap({ panelSelector: '> li' });
```

**Comment by albertogil** [comment]
It worked, thanks!
