### ISSUE TITLE
Implementing in a div

### ISSUE THREAD

**Issue by finchyz** [guidobouman/jquery-panelsnap#88]
Hello,
I have been trying for days now to implement this plugin on my Wordpress site - http//www.zactech.co.uk/ (note i haven't designed it yet - this theme is just taken from one of my other sites and stripped down). When I put the < section > tags in the header.php file, it worked perfectly (apart from the sites navigation bar was below the sections - kind of a big issue) I have called ".panel_container" instead of "body" the JS and tried "overflow:scroll" etc by looking around the issues on GitHub.
Sorry to be stupid - I know the issue will be staring me in the face.

Thanks,
Zac

**Comment by guidobouman** [comment]
Do you have pubic code I can take a look at?

**Comment by finchyz** [comment]
Can you view source it?

**Comment by guidobouman** [comment]
A completely failed to notice that you posted an URL. Will take a look in a bit.

**Comment by finchyz** [comment]
I'm really sorry, I forgot to disable maintenance mode, it should be visible now

**Comment by guidobouman** [comment]
Well, `$('body').panelSnap({ panelSelector: '.panel_container section.panel' });` Should work in your implementation. Trying to find out why I can't hook it in your site locally right now.

**Comment by finchyz** [comment]
Thanks, glad it isn't just me who is puzzled

**Comment by guidobouman** [comment]
Oh, no, don;t get me wrong, if you'll fix your implementation to `$('body').panelSnap({ panelSelector: '.panel_container section.panel' });` it should just work.

**Comment by finchyz** [comment]
I have added that code but it doesnt appear to work

**Comment by finchyz** [comment]
Do you think I have implemented it wrong?
