### ISSUE TITLE
Implementing in a <div>

### ISSUE THREAD

**Issue by finchyz** [guidobouman/jquery-panelsnap#90]
Hello,
I have been trying for days now to implement this plugin on my Wordpress site - http//www.zactech.co.uk/ (note i haven't designed it yet - this theme is just taken from one of my other sites and stripped down). When I put the < section > tags in the header.php file, it worked perfectly (apart from the sites navigation bar was below the sections - kind of a big issue) I have called ".panel_container" instead of "body" the JS and tried "overflow:scroll" etc by looking around the issues on GitHub.
I have tried this:
$('body').panelSnap({ panelSelector: '.panel_container section.panel' });
Sorry to be stupid - I know the issue will be staring me in the face.

Thanks,
Zac

**Comment by guidobouman** [comment]
You should call panelSnap on the element you want to scroll. If you have `overflow: scroll` on the `.panel_container` then this should work for you:

`$('.panel_container').panelSnap();`

Or if you have a different DOM layout:

`$('.panel_container').panelSnap({ panelSelector: 'section.panel' });`
