### ISSUE TITLE
Not working in Chrome?

### ISSUE THREAD

**Issue by JoshCarey** [guidobouman/jquery-panelsnap#94]
Hey there,

I've been trying to find a good scroll snapping solution for a project and I've found this one a few times.  Now that I've had time to start trying different scripts, this one doesn't seem to work anymore in Chrome.  At least the demo page isn't working:  http://guidobouman.github.io/jquery-panelsnap
I've asked a buddy to test the demo on his system and he says its not working for him either.

(BTW - I'm using Chrome version: 46.0.2490.80)

I'm just wanting to verify that its still working, or if there's a fix needed before I can try and implement this in my project.

**Comment by guidobouman** [comment]
Oh, yeah, the demo page has an old version which is broken in the most recent chrome builds. Havn;t updated the demo page in a while because I'm working on some improvements. Let me update that demo page for the public!

**Comment by guidobouman** [comment]
Demopage fixed & released v0.15.1 in the meantime.

Have fun.

**Comment by JoshCarey** [comment]
@guidobouman - Thanks, this seems to be working somewhat in Chrome.  It will work intermittently, but then it seems to get a partial or segmented snap position.  There were several instances where it would snap to like 4 or 5 different locations within the same panel.

You said that you're making improvements though, so hopefully you get the kinks worked out :)

**Comment by guidobouman** [comment]
What OS are you running? And are you able to record a video? That would help a lot. As I'm not experiencing this at all. :(

**Comment by JoshCarey** [comment]
I'm running OSX Yosemite 10.10.5 using a Magic Mouse.  Its definitely an intermittent thing.  When I open the demo in Safari and scroll the same way, it works flawlessly.  In Chrome, it will stutter and kind of get stuck between panels.  Sorry, I can't really easily do a video.

I found that if I do a standard kind of "scroll-lift" gesture like flicking, it works fine.  However if I do a scroll with my finger having constant contact with the mouse - "scroll-stop-lift scroll-stop-lift", that's when it will intermittently trigger a glitch in Chrome.  Like I said if I do it in Safari, it somehow works the same as the slight "flicking" motion scroll.
