### ISSUE TITLE
Detection of screen position fails with container

### ISSUE THREAD

**Issue by maxbeech** [guidobouman/jquery-panelsnap#98]
Hello!

Great plugin and great scrolling solution, have seen nothing else like it.
I have implemented the plugin and is working great. However I have tried to add links to buttons to jump to certain sections, and realised this cannot be done without implementing the menu system.
I have now done this but experienced an issue:

Having added a container for the content to make the menu work, the site now seems to fail at recognizing where the user is looking at. I think this because I have implemented another plugin which makes elements appear when the user scrolls to them, and now, unless I actually click on where the elements are hidden, they don't appear.

I have noticed I get this error (only with the container) in the chrome console: 
Uncaught TypeError: Cannot read property 'top' of undefined

Any help would be very much appreciated,
Max

**Comment by BEECHBOY707** [comment]
Here is a jsFiddle I created highlighting the issue: http://jsfiddle.net/beechboy707/uk30azcm/4/

**Comment by guidobouman** [comment]
Probably your waypoint plugin is watching the body scroll. And to implement the menu I think you added the wrapper div that does the scrolling. The waypoint plugin now thinks that you're not scrolling at all. Ask the author to implement an option to supply the scrolling element it needs to watch.

**Comment by guidobouman** [comment]
Actually: it already supports a context: https://jsfiddle.net/guidobouman/uk30azcm/15/

`context: '#wrapper'` does the trick.
