### ISSUE TITLE
It should go to the section that is the most present in the viewport.. 

### ISSUE THREAD

**Issue by Oblik-Design** [guidobouman/jquery-panelsnap#99]
If you"ve got three sections and let's say you go from the first to the second with a 1000ms delay, if you barely pass the second section (second section is 95% of the viewport), the plugin goes and snap to the third section, it make's no sens at all. It's obvious that the user was heading for the second section.. 

Sorry, eng is not my main language. 

So it should be calculated by half of window.scrollY of the section on screen, and the direction the user is heading(scroll direction).

**Comment by Oblik-Design** [comment]
http://daphnecaron.com

this is a good exemple on how it should work if you ask me ... :)

**Comment by guidobouman** [comment]
The plugin detects the direction you were scrolling, and always snaps in that direction. It's a design decision we made back in the day. That's just how the plugin works.
